<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <!-- Keep runtime redirects aligned with implementation assemblies, not reference assemblies. -->
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>True</UseWindowsForms>
    <ApplicationIcon>Images\App\icon.ico</ApplicationIcon>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AssemblyVersion>1.3.8</AssemblyVersion>
    <FileVersion>1.3.8</FileVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <None Remove="Images\App\align-horizontal.png" />
    <None Remove="Images\App\align-vertical.png" />
    <None Remove="Images\App\clear-folder.png" />
    <None Remove="Images\App\close.png" />
    <None Remove="Images\App\download.png" />
    <None Remove="Images\App\link.png" />
    <None Remove="Images\App\loading.png" />
    <None Remove="Images\App\logo.png" />
    <None Remove="Images\App\minimize.png" />
    <None Remove="Images\App\open-folder.png" />
    <None Remove="Images\App\refresh.jpg" />
    <None Remove="Images\App\refresh.png" />
    <None Remove="Images\Maps\AUTOHAVEN_WRECKERS\AZAROVS_RESTING_PLACE.png" />
    <None Remove="Images\Maps\AUTOHAVEN_WRECKERS\BLOOD_LODGE.png" />
    <None Remove="Images\Maps\AUTOHAVEN_WRECKERS\GAS_HEAVEN.png" />
    <None Remove="Images\Maps\AUTOHAVEN_WRECKERS\WRECKERS_YARD.png" />
    <None Remove="Images\Maps\AUTOHAVEN_WRECKERS\WRETCHED_SHOP.png" />
    <None Remove="Images\Maps\AZAROVSRESTINGPLACE.png" />
    <None Remove="Images\Maps\BACKWATER_SWAMP\GRIM_PANTRY.png" />
    <None Remove="Images\Maps\BACKWATER_SWAMP\THE_PALE_ROSE.png" />
    <None Remove="Images\Maps\BADHAMPRESCHOOLI.png" />
    <None Remove="Images\Maps\BADHAMPRESCHOOLII.png" />
    <None Remove="Images\Maps\BADHAMPRESCHOOLIII.png" />
    <None Remove="Images\Maps\BADHAMPRESCHOOLIV.png" />
    <None Remove="Images\Maps\BADHAMPRESCHOOLV.png" />
    <None Remove="Images\Maps\BLOODLODGE.png" />
    <None Remove="Images\Maps\COALTOWER.png" />
    <None Remove="Images\Maps\COLDWIND_FARM\FRACTURED_COWSHED.png" />
    <None Remove="Images\Maps\COLDWIND_FARM\RANCID_ABATTOIR.png" />
    <None Remove="Images\Maps\COLDWIND_FARM\ROTTEN_FIELDS.png" />
    <None Remove="Images\Maps\COLDWIND_FARM\THE_THOMPSON_HOUSE.png" />
    <None Remove="Images\Maps\COLDWIND_FARM\TORMENT_CREEK.png" />
    <None Remove="Images\Maps\CROTUS_PRENN_ASYLUM\DISTURBED_WARD.png" />
    <None Remove="Images\Maps\CROTUS_PRENN_ASYLUM\FATHER_CAMPBELLS_CHAPEL.png" />
    <None Remove="Images\Maps\DEADDAWGSALOON.png" />
    <None Remove="Images\Maps\DISTURBEDWARD.png" />
    <None Remove="Images\Maps\DVARKA_DEEPWOOD\NOSTROMO_WRECKAGE.png" />
    <None Remove="Images\Maps\DVARKA_DEEPWOOD\TOBA_LANDING.png" />
    <None Remove="Images\Maps\Empty.png" />
    <None Remove="Images\Maps\EYRIEOFCROWS.png" />
    <None Remove="Images\Maps\FAMILYRESIDENCE.png" />
    <None Remove="Images\Maps\FATHERCAMPBELLSCHAPEL.png" />
    <None Remove="Images\Maps\FORGOTTENRUINS.png" />
    <None Remove="Images\Maps\FORSAKEN_BONEYARD\EYRIE_OF_CROWS.png" />
    <None Remove="Images\Maps\FRACTUREDCOWSHED.png" />
    <None Remove="Images\Maps\GARDENOFJOY.png" />
    <None Remove="Images\Maps\GASHEAVEN.png" />
    <None Remove="Images\Maps\GIDEON_MEAT_PLANT\THE_GAME.png" />
    <None Remove="Images\Maps\GRAVE_OF_GLENVALE\DEAD_DAWG_SALOON.png" />
    <None Remove="Images\Maps\GREENVILLESQUARE.png" />
    <None Remove="Images\Maps\GRIMPANTRY.png" />
    <None Remove="Images\Maps\GROANINGSTOREHOUSE.png" />
    <None Remove="Images\Maps\HADDONFIELD\LAMPKIN_LANE.png" />
    <None Remove="Images\Maps\HAWKINS_NATIONAL_LABORATORY\THE_UNDERGROUND_COMPLEX.png" />
    <None Remove="Images\Maps\IRONWORKS OF MISERY.png" />
    <None Remove="Images\Maps\MIDWICHELEMNTARYSCHOOL.png" />
    <None Remove="Images\Maps\MOTHERSDWELLING.png" />
    <None Remove="Images\Maps\MOUNTORMONDRESORT.png" />
    <None Remove="Images\Maps\NOSTROMOWRECKAGE.png" />
    <None Remove="Images\Maps\NotReady.png" />
    <None Remove="Images\Maps\ORMOND\MOUNT_ORMOND_RESORT.png" />
    <None Remove="Images\Maps\ORMOND\MOUNT_ORMOND_RESORT_2.png" />
    <None Remove="Images\Maps\ORMOND\MOUNT_ORMOND_RESORT_3.png" />
    <None Remove="Images\Maps\ORMOND\ORMOND_LAKE_MINE.png" />
    <None Remove="Images\Maps\RACCOONCITYPOLICESTATIONEASTWING.png" />
    <None Remove="Images\Maps\RACCOONCITYPOLICESTATIONWESTWING.png" />
    <None Remove="Images\Maps\RACCOON_CITY\RACCOON_CITY_POLICE_STATION_EAST_WING.png" />
    <None Remove="Images\Maps\RACCOON_CITY\RACCOON_CITY_POLICE_STATION_WEST_WING.png" />
    <None Remove="Images\Maps\RANCIDABATTOIR.png" />
    <None Remove="Images\Maps\RED_FOREST\MOTHERS_DWELLING.png" />
    <None Remove="Images\Maps\RED_FOREST\THE_TEMPLE_OF_PURGATION.png" />
    <None Remove="Images\Maps\ROTTENFIELDS.png" />
    <None Remove="Images\Maps\SANCTUMOFWRATH.png" />
    <None Remove="Images\Maps\SHELTERWOODS.png" />
    <None Remove="Images\Maps\SILENT_HILL\MIDWICH_ELEMENTARY_SCHOOL.png" />
    <None Remove="Images\Maps\SILENT_HILL\MIDWICH_ELEMNTARY_SCHOOL.png" />
    <None Remove="Images\Maps\SPRINGWOOD\BADHAM_PRESCHOOL_I.png" />
    <None Remove="Images\Maps\SPRINGWOOD\BADHAM_PRESCHOOL_II.png" />
    <None Remove="Images\Maps\SPRINGWOOD\BADHAM_PRESCHOOL_III.png" />
    <None Remove="Images\Maps\SPRINGWOOD\BADHAM_PRESCHOOL_IV.png" />
    <None Remove="Images\Maps\SPRINGWOOD\BADHAM_PRESCHOOL_V.png" />
    <None Remove="Images\Maps\SUFFOCATIONPIT.png" />
    <None Remove="Images\Maps\THEGAME.png" />
    <None Remove="Images\Maps\THEGRIMPANTRY.png" />
    <None Remove="Images\Maps\THEPALEROSE.png" />
    <None Remove="Images\Maps\THESHATTEREDSQUARE.png" />
    <None Remove="Images\Maps\THETEMPLEOFPURGATION.png" />
    <None Remove="Images\Maps\THETHOMPSONHOUSE.png" />
    <None Remove="Images\Maps\THEUNDERGROUNDCOMPLEX.png" />
    <None Remove="Images\Maps\THE_DECIMATED_BORGO\FORGOTTEN_RUINS.png" />
    <None Remove="Images\Maps\THE_DECIMATED_BORGO\THE_SHATTERED_SQUARE.png" />
    <None Remove="Images\Maps\THE_MACMILLAN_ESTATE\COAL_TOWER.png" />
    <None Remove="Images\Maps\THE_MACMILLAN_ESTATE\COAL_TOWER_2.png" />
    <None Remove="Images\Maps\THE_MACMILLAN_ESTATE\GROANING_STOREHOUSE.png" />
    <None Remove="Images\Maps\THE_MACMILLAN_ESTATE\GROANING_STOREHOUSE_2.png" />
    <None Remove="Images\Maps\THE_MACMILLAN_ESTATE\IRONWORKS_OF_MISERY.png" />
    <None Remove="Images\Maps\THE_MACMILLAN_ESTATE\IRONWORKS_OF_MISERY_2.png" />
    <None Remove="Images\Maps\THE_MACMILLAN_ESTATE\SHELTER_WOODS.png" />
    <None Remove="Images\Maps\THE_MACMILLAN_ESTATE\SHELTER_WOODS_2.png" />
    <None Remove="Images\Maps\THE_MACMILLAN_ESTATE\SUFFOCATION_PIT.png" />
    <None Remove="Images\Maps\THE_MACMILLAN_ESTATE\SUFFOCATION_PIT_2.png" />
    <None Remove="Images\Maps\TOBALANDING.png" />
    <None Remove="Images\Maps\TORMENTCREEK.png" />
    <None Remove="Images\Maps\TREATMENTTHEATRE.png" />
    <None Remove="Images\Maps\WITHERED_ISLE\GARDEN_OF_JOY.png" />
    <None Remove="Images\Maps\WITHERED_ISLE\GREENVILLE_SQUARE.png" />
    <None Remove="Images\Maps\WRECKERSYARD.png" />
    <None Remove="Images\Maps\WRETCHEDSHOP.png" />
    <None Remove="Images\Maps\YAMAOKA_ESTATE\FAMILY_RESIDENCE.png" />
    <None Remove="Images\Maps\YAMAOKA_ESTATE\FAMILY_RESIDENCE_2.png" />
    <None Remove="Images\Maps\YAMAOKA_ESTATE\SANCTUM_OF_WRATH.png" />
    <None Remove="Images\Maps\YAMAOKA_ESTATE\SANCTUM_OF_WRATH_2.png" />
    <None Remove="Images\Recognition\test1.png" />
    <None Remove="Images\Recognition\test2.png" />
    <None Remove="Images\SurvivorStates\dead.png" />
    <None Remove="Images\SurvivorStates\escaped.png" />
    <None Remove="Images\SurvivorStates\hooked2.png" />
    <None Remove="Images\SurvivorStates\hooked3.png" />
    <None Remove="Images\SurvivorStates\sacrificed.png" />
    <None Remove="Images\SurvivorStates\sacrificed2.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="9.0.1" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.WindowsAPICodePack.Shell" Version="1.1.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.1" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\App\align-horizontal.png" />
    <Resource Include="Images\App\align-vertical.png" />
    <Resource Include="Images\App\clear-folder.png" />
    <Resource Include="Images\App\close.png" />
    <Resource Include="Images\App\download.png" />
    <Resource Include="Images\App\link.png" />
    <Resource Include="Images\App\loading.png" />
    <Resource Include="Images\App\logo.png" />
    <Resource Include="Images\App\open-folder.png" />
    <Resource Include="Images\App\refresh.png" />
    <Resource Include="Images\Maps\AUTOHAVEN_WRECKERS\AZAROVS_RESTING_PLACE.png" />
    <Resource Include="Images\Maps\AUTOHAVEN_WRECKERS\BLOOD_LODGE.png" />
    <Resource Include="Images\Maps\AUTOHAVEN_WRECKERS\GAS_HEAVEN.png" />
    <Resource Include="Images\Maps\AUTOHAVEN_WRECKERS\WRECKERS_YARD.png" />
    <Resource Include="Images\Maps\AUTOHAVEN_WRECKERS\WRETCHED_SHOP.png" />
    <Resource Include="Images\Maps\BACKWATER_SWAMP\GRIM_PANTRY.png" />
    <Resource Include="Images\Maps\BACKWATER_SWAMP\THE_PALE_ROSE.png" />
    <Resource Include="Images\Maps\COLDWIND_FARM\FRACTURED_COWSHED.png" />
    <Resource Include="Images\Maps\COLDWIND_FARM\RANCID_ABATTOIR.png" />
    <Resource Include="Images\Maps\COLDWIND_FARM\ROTTEN_FIELDS.png" />
    <Resource Include="Images\Maps\COLDWIND_FARM\THE_THOMPSON_HOUSE.png" />
    <Resource Include="Images\Maps\COLDWIND_FARM\TORMENT_CREEK.png" />
    <Resource Include="Images\Maps\CROTUS_PRENN_ASYLUM\DISTURBED_WARD.png" />
    <Resource Include="Images\Maps\CROTUS_PRENN_ASYLUM\FATHER_CAMPBELLS_CHAPEL.png" />
    <Resource Include="Images\Maps\DVARKA_DEEPWOOD\NOSTROMO_WRECKAGE.png" />
    <Resource Include="Images\Maps\DVARKA_DEEPWOOD\TOBA_LANDING.png" />
    <Resource Include="Images\Maps\Empty.png" />
    <Resource Include="Images\Maps\FORSAKEN_BONEYARD\EYRIE_OF_CROWS.png" />
    <Resource Include="Images\Maps\GIDEON_MEAT_PLANT\THE_GAME.png" />
    <Resource Include="Images\Maps\GRAVE_OF_GLENVALE\DEAD_DAWG_SALOON.png" />
    <Resource Include="Images\Maps\HADDONFIELD\LAMPKIN_LANE.png" />
    <Resource Include="Images\Maps\HAWKINS_NATIONAL_LABORATORY\THE_UNDERGROUND_COMPLEX.png" />
    <Resource Include="Images\Maps\NotReady.png" />
    <Resource Include="Images\Maps\ORMOND\MOUNT_ORMOND_RESORT.png" />
    <Resource Include="Images\Maps\ORMOND\MOUNT_ORMOND_RESORT_2.png" />
    <Resource Include="Images\Maps\ORMOND\MOUNT_ORMOND_RESORT_3.png" />
    <Resource Include="Images\Maps\ORMOND\ORMOND_LAKE_MINE.png" />
    <Resource Include="Images\Maps\RACCOON_CITY\RACCOON_CITY_POLICE_STATION_EAST_WING.png" />
    <Resource Include="Images\Maps\RACCOON_CITY\RACCOON_CITY_POLICE_STATION_WEST_WING.png" />
    <Resource Include="Images\Maps\RED_FOREST\MOTHERS_DWELLING.png" />
    <Resource Include="Images\Maps\RED_FOREST\THE_TEMPLE_OF_PURGATION.png" />
    <Resource Include="Images\Maps\SILENT_HILL\MIDWICH_ELEMENTARY_SCHOOL.png" />
    <Resource Include="Images\Maps\SPRINGWOOD\BADHAM_PRESCHOOL_I.png" />
    <Resource Include="Images\Maps\SPRINGWOOD\BADHAM_PRESCHOOL_II.png" />
    <Resource Include="Images\Maps\SPRINGWOOD\BADHAM_PRESCHOOL_III.png" />
    <Resource Include="Images\Maps\SPRINGWOOD\BADHAM_PRESCHOOL_IV.png" />
    <Resource Include="Images\Maps\SPRINGWOOD\BADHAM_PRESCHOOL_V.png" />
    <Resource Include="Images\Maps\THE_DECIMATED_BORGO\FORGOTTEN_RUINS.png" />
    <Resource Include="Images\Maps\THE_DECIMATED_BORGO\THE_SHATTERED_SQUARE.png" />
    <Resource Include="Images\Maps\THE_MACMILLAN_ESTATE\COAL_TOWER.png" />
    <Resource Include="Images\Maps\THE_MACMILLAN_ESTATE\COAL_TOWER_2.png" />
    <Resource Include="Images\Maps\THE_MACMILLAN_ESTATE\GROANING_STOREHOUSE.png" />
    <Resource Include="Images\Maps\THE_MACMILLAN_ESTATE\GROANING_STOREHOUSE_2.png" />
    <Resource Include="Images\Maps\THE_MACMILLAN_ESTATE\IRONWORKS_OF_MISERY.png" />
    <Resource Include="Images\Maps\THE_MACMILLAN_ESTATE\IRONWORKS_OF_MISERY_2.png" />
    <Resource Include="Images\Maps\THE_MACMILLAN_ESTATE\SHELTER_WOODS.png" />
    <Resource Include="Images\Maps\THE_MACMILLAN_ESTATE\SHELTER_WOODS_2.png" />
    <Resource Include="Images\Maps\THE_MACMILLAN_ESTATE\SUFFOCATION_PIT.png" />
    <Resource Include="Images\Maps\THE_MACMILLAN_ESTATE\SUFFOCATION_PIT_2.png" />
    <Resource Include="Images\Maps\WITHERED_ISLE\GARDEN_OF_JOY.png" />
    <Resource Include="Images\Maps\WITHERED_ISLE\GREENVILLE_SQUARE.png" />
    <Resource Include="Images\Maps\YAMAOKA_ESTATE\FAMILY_RESIDENCE.png" />
    <Resource Include="Images\Maps\YAMAOKA_ESTATE\FAMILY_RESIDENCE_2.png" />
    <Resource Include="Images\Maps\YAMAOKA_ESTATE\SANCTUM_OF_WRATH.png" />
    <Resource Include="Images\Maps\YAMAOKA_ESTATE\SANCTUM_OF_WRATH_2.png" />
    <Resource Include="Images\SurvivorStates\dead.png" />
    <Resource Include="Images\SurvivorStates\escaped.png" />
    <Resource Include="Images\SurvivorStates\hooked.png" />
    <Resource Include="Images\SurvivorStates\hooked2.png" />
    <Resource Include="Images\SurvivorStates\hooked3.png" />
    <Resource Include="Images\SurvivorStates\sacrificed.png" />
    <Resource Include="Images\SurvivorStates\sacrificed2.png" />
    <Content Include="Images\App\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Images\App\AppImages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppImages.resx</DependentUpon>
    </Compile>
    <Compile Update="Images\Maps\MapImages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MapImages.resx</DependentUpon>
    </Compile>
    <Compile Update="Images\SurvivorStates\SurvivorStates.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SurvivorStates.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Images\App\AppImages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>AppImages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Images\Maps\MapImages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MapImages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Images\SurvivorStates\SurvivorStates.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SurvivorStates.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Net.Http" />
  </ItemGroup>

</Project>
